### ISSUE TITLE
"Function already exists" errors during installation

### ISSUE THREAD

**Issue by xhevahir** [ardagnir/vimbed#3]
Any idea how to fix these? (I don't know much about Vimscript.)
line  262:
E122: Function <SNR>82_WriteTabFile already exists, add ! to replace it
line  306:
E122: Function <SNR>82_BetterShellEscape already exists, add ! to replace it

**Comment by ardagnir** [comment]
Vimbed is being initialized twice. You can allow this by adding !'s to those two functions(look at all the other functions).

**Comment by xhevahir** [comment]
Thanks. I didn't know the ! operator came immediately after the 'function' keyword.
