### ISSUE TITLE
Can I test for a vimbed environment in my .vimrc?

### ISSUE THREAD

**Issue by cambrant** [ardagnir/vimbed#4]
I have a few settings in my .vimrc which are problematic when I use vimbed with athame. One or more of the options wrap, linebreak, wrapmargin and textwidth is causing my athame shell to only accept a maximum of 80 characters, which gets tricky when typing or pasting long commands.

Preferably, I'd like to be able to use an if-statement to only use certain settings if not running vim in an athame environment. Is that possible at all? `if !exists("g:loaded_vimbed")` doesn't do anything, and I find it hard to debug why. Any help would be great.

**Comment by ardagnir** [comment]
Your vimrc is probably being loaded before vimbed. You should be able to disable wrap in the athamerc though(I'll probably add that to the default athamerc soon). If you want to do everything in the vimrc, you might have to use an autocmd to wait for vim to load.

**Comment by cambrant** [comment]
I can confirm I get the expected behavior with the following options in my ~/.athamerc:

set nowrap
set nolinebreak
set textwidth=0

Thank you for the help, and sorry about the misunderstanding. I thought this would be a vimbed issue!
